plugins {
  id 'application'
}

group = 'io.github.sausagegame'
version = '1.0.0-SNAPSHOT'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':backend')
}

application {
  mainClass = 'io.github.sausagegame.cli.CliLauncher'
}
